CREATE TABLE lists (
	list_id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	card_id VARCHAR(255) NOT NULL,
	list_name VARCHAR(255) NOT NULL
);

CREATE TABLE elements (
	element_id INTEGER  AUTO_INCREMENT PRIMARY KEY,
	list_id INTEGER NOT NULL,
	element_name VARCHAR(255) NOT NULL,
	description VARCHAR(255),
	quantity INTEGER DEFAULT 1,
	element_is_bought INTEGER(1) DEFAULT 0
);
	